// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGldl7CMCP8FAWF0ynqykTBvSVC_QeeKY',
    appId: '1:742479284222:web:bc3b8a36b443d7e62922af',
    messagingSenderId: '742479284222',
    projectId: 'pomoflow-app',
    authDomain: 'pomoflow-app.firebaseapp.com',
    storageBucket: 'pomoflow-app.firebasestorage.app',
    measurementId: 'G-4GE2X65GB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhiw_zZYNonN0Ha1ldE5-WzOWIxXUao2A',
    appId: '1:742479284222:android:651e7a274ec25f902922af',
    messagingSenderId: '742479284222',
    projectId: 'pomoflow-app',
    storageBucket: 'pomoflow-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC48n3JP9LWOxpTEwk-8AVzmB1Vf4wJYCY',
    appId: '1:742479284222:ios:a013e4767c7d0f042922af',
    messagingSenderId: '742479284222',
    projectId: 'pomoflow-app',
    storageBucket: 'pomoflow-app.firebasestorage.app',
    iosBundleId: 'br.app.pomoflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC48n3JP9LWOxpTEwk-8AVzmB1Vf4wJYCY',
    appId: '1:742479284222:ios:b76a503fe50dac8d2922af',
    messagingSenderId: '742479284222',
    projectId: 'pomoflow-app',
    storageBucket: 'pomoflow-app.firebasestorage.app',
    iosBundleId: 'com.example.pomoflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGldl7CMCP8FAWF0ynqykTBvSVC_QeeKY',
    appId: '1:742479284222:web:5d43af607964f45d2922af',
    messagingSenderId: '742479284222',
    projectId: 'pomoflow-app',
    authDomain: 'pomoflow-app.firebaseapp.com',
    storageBucket: 'pomoflow-app.firebasestorage.app',
    measurementId: 'G-PLK5EPY0BS',
  );
}
